// src/lib/sections/Header.svelte
<script lang="ts">
  import { IconBrandDiscord, IconBrandGithub, IconBrandInstagram, IconBrandLinkedin, IconBrandTwitter, IconBrandYoutube } from "$lib/components/icons";
</script>

<section>
  <img src="/images/banner_kitty.jpeg" alt="Kitty's Banner" class="h-96 w-full object-cover block object-center transition-all" />

  <div class="shrink-0 flex items-center justify-start mx-auto w-5/6 lg:w-2/4">
    <img alt="profile" class="-mt-16 h-32 w-32 rounded-full border-white" src="/images/profile_noisette.jpeg" />

    <div class="flex flex-col justify-center ml-auto sm:bg-[#161616] sm:rounded-lg sm:shadow-lg sm:overflow-hidden">
      <ul class="flex flex-row justify-end text-white gap-2 p-2">
        <a href="https://github.com/Steellgold" class="block hover:text-white transition-all"><IconBrandGithub /></a>
        <a href="https://discord.com/users/504392983244832780" class="block hover:text-gray-600 transition-all"><IconBrandDiscord /></a>
        <a href="https://youtube.com/c/Steellgold" class="block hover:text-red-600 transition-all"><IconBrandYoutube /></a>
        <a href="https://instagram.com/steellgold" class="block hover:text-pink-600 transition-all"><IconBrandInstagram /></a>
        <a href="https://twitter.com/Steellgold" class="block hover:text-blue-600 transition-all"><IconBrandTwitter /></a>
        <a href="https://linkedin.com/in/gaetanhus" class="block hover:text-blue-600 transition-all"><IconBrandLinkedin /></a>
      </ul>
    </div>
  </div>

  <div id="about" class="pt-9 text-white flex flex-col justify-center mx-auto w-5/6 lg:w-2/4">
    <p class="text-1xl pt-1 text-left">Salut, moi c'est</p>
    <h1 class="text-5xl font-bold text-left">Gaëtan</h1>
    <p class="text-1xl pt-1 text-left">Je suis développeur back-end sur TypeScript, ainsi que sur PHP.</p>
  </div>
</section>

// src/app/_components/header.tsx
"use client";

import { Alert, AlertDescription, AlertTitle } from "@/lib/components/ui/alert";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/lib/components/ui/tooltip";
import { ImageZoomer } from "image-zoomer-react";
import { HiglightedSpan } from "@/lib/config/projects";
import { useLang } from "@/lib/stores/lang.store";
import { useInitializeViewMode, useViewMode } from "@/lib/stores/mode.store";
import { cn } from "@/lib/utils";
import { dayJS } from "@/lib/utils/dayjs/day-js";
import { Cake, ExternalLink, Github, Instagram, Linkedin, Mail, MapPin, Twitter } from "lucide-react";
import Link from "next/link";
import { ReactElement } from "react";
import Image from "next/image";

type SocialLink = {
  href: string;
  icon: ReactElement;
  title: string;
  showOnCv?: boolean;
  className?: string;
}

const SocialLinks: SocialLink[] = [ {
    href: "https://github.com/Steellgold",
    icon: <Github size={18} strokeWidth={2} />,
    title: "GitHub",
    className: "dark:hover:text-white transition-all hover:rotate-12",
    showOnCv: true
  }, {
    href: "https://linkedin.com/in/gaetanhus",
    icon: <Linkedin size={18} strokeWidth={2} />,
    title: "LinkedIn",
    className: "hover:text-blue-600 transition-all hover:-rotate-12",
    showOnCv: true
  }, {
    href: "https://www.malt.fr/profile/gaetanhuszovits",
    icon: <ExternalLink size={18} strokeWidth={2} />,
    title: "Malt (Freelance)",
    className: "hover:text-[#fc5757] transition-all hover:rotate-12",
    showOnCv: true
  }, {
    href: "mailto:pro@gaetanhus.fr",
    icon: <Mail size={18} strokeWidth={2} />,
    title: "Email",
    className: "hover:text-red-600 transition-all hover:rotate-12",
    showOnCv: true
  }, {
    href: "https://twitter.com/Steellgold",
    icon: <Twitter size={18} strokeWidth={2} />,
    title: "Twitter",
    className: "hover:text-blue-600 transition-all hover:rotate-12",
    showOnCv: false
  }, {
    href: "https://instagram.com/steellgold",
    icon: <Instagram size={18} strokeWidth={2} />,
    title: "Instagram",
    className: "hover:text-pink-600 transition-all hover:-rotate-12",
    showOnCv: false
  }
]

export const Header = (): ReactElement => {
  const { viewMode } = useViewMode();
  useInitializeViewMode()
  const { lang } = useLang();

  return (
    <section>
      {viewMode == "normal" && (
        <div className="relative">
          <ImageZoomer
            as={Image}
            src="/_static/images/MY_CATS.jpg"
            alt="MY BEAUTIFUL CATS IS SO CUTEEEEEEEEEEEEEEEEEEEEE AMAZING <3 <3 <3 alt text"
            className={cn(
              "w-full object-cover block object-center border-white dark:border-[#121212] md:border-[10px] md:rounded-3xl",
              "h-[250px] lg:h-[350px] xl:h-[400px]"
            )}
            quality={100}
            width={3000}
            height={1810}
          />
        </div>
      )}

      {viewMode == "cv" && <div className="w-full h-[100px] lg:h-[100px] xl:h-[100px]" />}

      <div className="shrink-0 flex items-center justify-start mx-auto w-5/6 lg:w-2/4">
        <ImageZoomer
          as={Image}
          alt="profile"
          className={cn(
            "-mt-16 h-32 w-32 rounded-lg transform transition-all hover:scale-110", {
              "border-white dark:border-[#121212] border-[5px] hover:border-[3.5px]": viewMode == "normal",
            }
          )}
          src={"/_static/images/me2.jpg"}
          width={128}
          height={128}
        />


        <div className="flex flex-col justify-center ml-auto border dark:border-0 dark:bg-[#242222] sm:rounded-lg dark:shadow-lg sm:overflow-hidden">
          <ul className="flex flex-row justify-end dark:text-white gap-2 p-2">
            <div className="flex gap-2">
              <TooltipProvider delayDuration={100}>
                {SocialLinks.filter((link) => link.showOnCv === true).map((link) => (
                  <Tooltip key={link.href}>
                    <TooltipTrigger>
                      <Link href={link.href} passHref className={cn("block", link.className)}>
                        {link.icon}
                      </Link>
                    </TooltipTrigger>
                    <TooltipContent>
                      {link.title}
                    </TooltipContent>
                  </Tooltip>
                ))}
              </TooltipProvider>
            </div>
              
            <div className={cn("flex gap-2", {
              "hidden": viewMode == "cv"
            })}>
              <TooltipProvider delayDuration={100}>
                {SocialLinks.filter((link) => link.showOnCv !== true).map((link) => (
                  <Tooltip key={link.href}>
                    <TooltipTrigger>
                      <Link href={link.href} passHref className={cn("block", link.className)}>
                        {link.icon}
                      </Link>
                    </TooltipTrigger>
                    <TooltipContent>
                      {link.title}
                    </TooltipContent>
                  </Tooltip>
                ))}
              </TooltipProvider>
            </div>
          </ul>
        </div>
      </div>

      <div className="pt-3 dark:text-white flex flex-col justify-center mx-auto w-5/6 lg:w-2/4">
        <p className="text-1xl pt-1 text-left">
          {viewMode == "normal"
            ? lang == "en" ? "Hi, I'm" : "Salut, je suis"
            : lang == "en" ? "Hello, I'm" : "Bonjour, je suis"
          }
        </p>

        <h1 className="flex flex-row items-center gap-2">
          <span className="text-5xl font-bold">{viewMode == "normal" ? "Gaëtan" : "Gaëtan Huszovits"}</span>
          {viewMode == "cv" && <span className="hidden sm:flex text-[#f0f0f0] bg-[#252525] px-2 py-1 rounded-md mt-2.5 text-xs gap-1 items-center">
            <MapPin className="h-3 w-3" /> Kingersheim, France
          </span>}
        </h1>
        
        <p className="text-1xl pt-1 text-left">
          {viewMode == "normal"
            ? <>{lang == "en" ? <>I&apos;m a full-stack developer, working with TypeScript.</>
              : <>Je suis un développeur full-stack, travaillant avec TypeScript.</>}</>
            
            : <>{lang == "en" ? <>I have {dayJS().diff("2004-10-14", "years")} years old and I am a full-stack developer with <HiglightedSpan>NextJS</HiglightedSpan>, and <HiglightedSpan>TypeScript</HiglightedSpan>.</>
              : <>J&apos;ai {dayJS().diff("2004-10-14", "years")} ans et je suis un développeur full-stack, avec React avec <HiglightedSpan>NextJS</HiglightedSpan>, et <HiglightedSpan>TypeScript</HiglightedSpan>.</>}</>
          }
        </p>

        {dayJS().format("MM-DD") === "10-14" && viewMode == "normal" && (
          <Alert className="mt-3">
            <Cake className="h-4 w-4" />
            {lang == "en" ? <>
              <AlertTitle>It&apos;s my birthday, i&apos;m {dayJS().diff("2004-10-14", "years")} years old!</AlertTitle>
              <AlertDescription>Confetti is falling from the sky!</AlertDescription>
            </> : <>
              <AlertTitle>C&apos;est mon anniversaire, j&apos;ai {dayJS().diff("2004-10-14", "years")} ans!</AlertTitle>
              <AlertDescription>Des confettis tombent du ciel!</AlertDescription>
            </>}
          </Alert>
        )}
      </div>
    </section>
  )
}
