// src/lib/components/project/project-card.svelte
<script lang="ts">
  import type { Project } from "$lib/config/project.types";

  export let project: Project;
</script>

<!-- Card -->
<div class="bg-[#161616] rounded-lg shadow-lg overflow-hidden">
  <div class="p-4">
    <div class="flex flex-row justify-between items-center">
      <h3 class="text-lg font-semibold text-white">{project.title}</h3>
      {#if project.link}
        {#if project.type == "Open Source"}
          <a href={project.link} class="text-sm text-white bg-green-700 px-1 rounded hover:text-gray-300 transition-all">
            Open Source
          </a>
        {:else if project.type == "Pro"}
          <a href={project.link} class="text-sm text-white bg-gray-700 px-1 rounded hover:text-gray-300 transition-all">
            Pro
          </a>
        {/if}
      {/if}
    </div>
    <p class="text-gray-400">{project.description}</p>

    <!-- Skills -->
    <div>
      <div class="flex flex-row gap-2 mt-4">
        <div class="flex flex-row items-center gap-2 text-sm text-gray-400">
          {#each project.skills as skill}
            <span>{skill.name}</span>
          {/each}
        </div>
      </div>
    </div>
  </div>
</div>

// src/lib/components/project.card.tsx
import Link from "next/link";
import { Project } from "../config/types/project.type";
import { cn } from "../utils";
import { Card, CardDescription, CardFooter, CardHeader, CardTitle } from "./ui/card";
import { Component } from "./utils/component";
import { ExternalLink } from "lucide-react";
import { PropsWithChildren } from "react";
import { CustomCard } from "./card";

export const ProjectCard: Component<Project & { className?: string }> = ({ title, description, stacks, url, duration, type, className }) => {
  return (
    <SurroundLink href={url} className={cn("cursor-pointer", className)}>
      <CustomCard>
        <CardHeader className="p-4">
          <div className="flex justify-between items-center">
            <div className="flex flex-col">
              <CardTitle className={cn("text-[#f0f0f0]", { "flex items-center": url !== "" })}>
                {title}
                {url ? <ExternalLink className="w-4 h-4 ml-2" /> : null}
              </CardTitle>

              <CardDescription className="text-[#f5f1de] text-xs mt-1.5">
                {duration.start.format("DD MMM YYYY")} → {duration.end ? duration.end.format("DD MMM YYYY") : "Today"}
              </CardDescription>
            </div>
            
            {type === "pro" && <span className="text-[#181b20] bg-[#f5f1de] px-2 py-1 rounded-md text-xs">Pro</span>}
          </div>
          <CardDescription>{description}</CardDescription>
        </CardHeader>

        <CardFooter className="p-4">
          <div className="flex flex-wrap gap-1">
            {stacks.map((stack) => (
              <span key={stack.name} className="text-[#f0f0f0] bg-[#333] px-2 py-1 rounded-md text-xs">
                {stack.name}
              </span>
            ))}
          </div>
        </CardFooter>
      </CustomCard>
    </SurroundLink>
  );
}

const SurroundLink: Component<PropsWithChildren & { href?: string, className?: string }> = ({ href, children, className }) => {
  if (!href) return children as any;

  return (
    <Link href={href} passHref className={className}>
      {children}
    </Link>
  );
}
