// src/routes/sections/__projects.svelte
<script lang="ts">
  import { ProjectCard } from "$lib/components/project";
  import { projects } from "$lib/config/projects";
</script>

<section>
  <div class="pt-3 shrink-0 grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-3 items-center justify-start mx-auto w-5/6 lg:w-2/4">
    {#each projects as project}
      <ProjectCard {project} />
    {/each}
  </div>
</section>

// src/app/lib/projects.tsx
import { ProjectCard } from "@/lib/components/project.card";
import { projects } from "@/lib/config/projects";
import { cn } from "@/lib/utils";
import { ReactElement } from "react";

export const Projects = (): ReactElement => {

  const isOdd = projects.length % 2 !== 0;

  return (
    <div className={cn("grid gap-3", {
      "md:grid-cols-2": projects.length > 1,
    })}>
      {projects.map((project, index) => (
        <ProjectCard {...project} key={project.title} className={cn({
          "md:col-span-2": isOdd && index === projects.length - 1
        })} /> 
      ))}
    </div>
  );
}
